# Generated by Django 4.0 on 2021-12-12 14:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Learn_App', '0003_alter_student_admission_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
